apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: roshand1/multi-reactapp
      context: ReactBolerPlateWithWebpackExpress
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml