version: '3'

services: 
  redis-server:
    image: 'redis'
  node-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - .:/app
