## This config file will create a cluster in aws
## with configured vpc and subnet id that way 
## if you applications are in same vpc you could access them
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: hg-pes-admin
  region: us-east-1
vpc:
  id: vpc-dfaread
  subnets:
    public:
      us-east-1a: { id: subnet-6c3edfad525 }
      us-east-1b: { id: subnet-3107dfad856a }
      us-east-1d: { id: subnet-46d25dafaa6b }
    private:
      us-east-1a: { id: subnet-6b3e4fadad522 }
      us-east-1b: { id: subnet-350fad7856e }
      us-east-1d: { id: subnet-44d2dfa5a69 }
nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 10
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: m5.2xlarge
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true